### ISSUE TITLE
Support for custom file formats

### ISSUE THREAD

**Issue by Fuhrmann** [jacebrowning/datafiles#134]
Hi, thanks for your work.

I'm developing an GUI application using python. Its basic a wrapper for a configuration file that is using the yaml format.

The problem is that this file is using ".conf" extension. This is done by the original package and I can not change this behavior.

When I try to load the file I get the following error: `Unsupported file extension: .conf`. This is understandable, but I would like to know if there it is a way to add support for custom file formats?

**Comment by jacebrowning** [comment]
I envision a few ways we could achieve this:

```python
from datafiles import datafile, formats

@datafile("my-file-path.conf", format=formats.YAML)
class MyConfig:
   ...
```

```python
from datafiles import datafile

@datafile("my-file-path.conf", format='yml')
class MyConfig:
   ...
```

```python
from datafile import datafile, formats

formats.register('.conf', formats.YAML)

@datafile("my-file-path.conf")
class MyConfig:
    ...
```

Would any of these work well for your use case?
Can you think of any other way to register `.conf` as YAML for you program?

**Comment by Fuhrmann** [comment]
This solution would be the most flexible, since it maybe allow me to register custom formats that this package doesn't support?

```
from datafile import datafile, formats

formats.register('.conf', formats.YAML)

@datafile("my-file-path.conf")
class MyConfig:
    ...

```

If you think the suggestion above would take a lot work to develop, I would suggest your first solution:

```
from datafiles import datafile, formats

@datafile("my-file-path.conf", format=formats.YAML)
class MyConfig:
   ...
```

**Comment by jacebrowning** [comment]
The registration system is available in this beta release: https://pypi.org/project/datafiles/0.6b1/

Documentation: https://datafiles.readthedocs.io/en/latest/formats/#custom-formats

**Comment by Fuhrmann** [comment]
This was fast. Thank you for helping me. I'll check it out!
