### ISSUE TITLE
Model.objects.all() doesn't fill values

### ISSUE THREAD

**Issue by ramnes** [jacebrowning/datafiles#139]
Take the following `test.yaml` file

```yaml
value: test
```

and run the following snippet

```python
from datafiles import datafile

@datafile("{self.name}.yaml")
class Sample:
    name: str
    value: str

for sample in Sample.objects.all():
    print(sample)
```

and you get an incomplete model:

```
INFO: datafiles.manager: Finding files matching pattern: *.yaml
Sample(name='test', value=<class 'dataclasses._MISSING_TYPE'>)
```

The file is properly found, the name is properly parsed, but arguments that should be passed to the model aren't.

Also, by trying to find the root cause, I found this part of the code, in which the loop and its hard coded number of iterations seem hackish at best:
 https://github.com/jacebrowning/datafiles/blob/f9c9771d0742afd6545107bbc1c937b77430bf48/datafiles/manager.py#L37-L43

**Comment by jacebrowning** [comment]
Thanks for the bug report @ramnes. I'll work on a fix.

The `range(9)` is indeed a hack as I couldn't find a simple way to determine how many positional arguments an object constructor takes to fill in placeholders. Any suggestions?

**Comment by ramnes** [comment]
Do you want the test implemented in https://github.com/jacebrowning/datafiles/commit/c3d419080a41b02419d72122aa667d787e8a4dd8 fixed before closing this?

**Comment by jacebrowning** [comment]
No, I'll open a new issue describe the remaining anomaly and get a new release up.

**Comment by jacebrowning** [comment]
The fix for this issue is available here: https://pypi.org/project/datafiles/0.6b3/

**Comment by ramnes** [comment]
Thank you!
