### ISSUE TITLE
Document (or implement) changing the log level

### ISSUE THREAD

**Issue by frankgerhardt** [jacebrowning/datafiles#175]
I have 300 datafiles and I get a lot of INFO. Is it possible to change the log level to WARNING?

**Comment by jacebrowning** [comment]
`datafiles` relies on https://minilog.readthedocs.io so you should be able to:

```
import log
log.silence('datafiles', allow_warning=True)
```

...but I'll think about a way to control this at the library level.

**Comment by frankgerhardt** [comment]
Thank you! It works after `log.reset()`.

**Comment by jacebrowning** [comment]
That's good to hear! The crux of the issue is that `datafiles` logs in the `@datafile()` decorator before any of a user's code runs. Perhaps libraries shouldn't log in decorator calls, but there's a good amount of debugging information provided therein.

**Comment by jacebrowning** [comment]
https://pypi.org/project/datafiles/0.10b2/ should provide a way to silence the `datafiles` logger before models are created as described here: https://datafiles.readthedocs.io/en/latest/logging/

**Comment by jacebrowning** [comment]
@frankgerhardt https://pypi.org/project/datafiles/0.11b4/ removes the automatic logging configuration entirely, so that may work better for you.
