### ISSUE TITLE
Add support for Mapping and MutableMapping

### ISSUE THREAD

**Issue by colltoaction** [jacebrowning/datafiles#183]
Hi!

I just hit this error in a very simple class:

```py
@datafile("file.yaml")
class ClassWithMapping:
    mapping: Mapping[str, str]
```

```
Traceback (most recent call last):
  File "/Users/colltoaction/.local/share/virtualenvs/redacted/lib/python3.7/site-packages/datafiles/model.py", line 95, in modified_init
    Model.__post_init__(self)
  File "/Users/colltoaction/.local/share/virtualenvs/redacted/lib/python3.7/site-packages/datafiles/model.py", line 18, in __post_init__
    self.datafile = create_mapper(self)
  File "/Users/colltoaction/.local/share/virtualenvs/redacted/lib/python3.7/site-packages/datafiles/mapper.py", line 293, in create_mapper
    attrs[field.name] = map_type(field.type, name=field.name)
  File "/Users/colltoaction/.local/share/virtualenvs/redacted/lib/python3.7/site-packages/datafiles/converters/__init__.py", line 50, in map_type
    converters[field.name] = map_type(field.type, name=field.name)
  File "/Users/colltoaction/.local/share/virtualenvs/redacted/lib/python3.7/site-packages/datafiles/converters/__init__.py", line 88, in map_type
    raise TypeError(f'Unsupported container type: {cls.__origin__}')
TypeError: Unsupported container type: <class 'collections.abc.Mapping'>
```

I'm not sure if it's possible to just use the `Dictionary` container with these, but if it was this would be a fairly simple change. Otherwise, maybe adding a specific error message [here](https://github.com/jacebrowning/datafiles/blob/40c6db10c6a64495f5bdc846a7d7e9067588a138/datafiles/converters/__init__.py#L88) indicating to use the `Dict` typing would be great for UX.

https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes

Thanks and great project!

**Comment by jacebrowning** [comment]
Thanks for the report!

I'm actually not too familiar with the `Mapping` annotation. When would that be used over `Dict`? My guess is that we could simply `map_type(Mapping) => Dictionary` for serialization purposes. Can you show an example of how `ClassWithMapping` might be used in practice?

**Comment by colltoaction** [comment]
From the docs:

https://docs.python.org/3/library/typing.html#typing.Dict

> `class typing.Dict(dict, MutableMapping[KT, VT])`
> 
> A generic version of dict. Useful for annotating return types. To annotate arguments it is preferred to use an abstract collection type such as Mapping.

https://docs.python.org/3/glossary.html#term-mapping

> A container object that supports arbitrary key lookups and implements the methods specified in the Mapping or MutableMapping abstract base classes. Examples include dict, collections.defaultdict, collections.OrderedDict and collections.Counter.

The idea is that the abstract collections such as `Mapping` define a smaller interface. As a user, you specify that you only care about having a `__getitem__` method, and don't care about the object being an actual `dict` instance.

I also just found about `TypedDict`, which covers the same use case of nested structures that you implemented with dataclasses:

* https://datafiles.readthedocs.io/en/latest/types/containers/#dataclasses
* https://www.python.org/dev/peps/pep-0589/

**Comment by jacebrowning** [comment]
https://github.com/jacebrowning/datafiles/pull/185 contains a patch to consider all subtypes of `Mapping` to be dictionaries.

Does that seem to meet your use case?

**Comment by colltoaction** [comment]
That's fantastic!

**Comment by jacebrowning** [comment]
This fix is available here: https://pypi.org/project/datafiles/0.11b1/
