### ISSUE TITLE
Does this work with attrs classes and/or dicts

### ISSUE THREAD

**Issue by BrendanSimon** [jacebrowning/datafiles#191]
This looks like a great way to share python data objects between processes - yes/no?

attrs is like dataclasses on steroids.  Can attrs be used with datafiles?

I presume I cannot use dictionaries for arbitrary data sharing (given the requirement to use dataclasses).

Is there anyway I can use datafiles to share a dict objects between processes?

Thanks, Brendan.

**Comment by jacebrowning** [comment]
> This looks like a great way to share python data objects between processes - yes/no?

Yeah, if you're comfortable using the filesystem as the sharing mechanism. Multiple processes can read and write to the same datafile.

> attrs is like dataclasses on steroids. Can attrs be used with datafiles?

`datafiles` relies on type annotations to serialize objects, which requires the dataclasses standard library APIs. 

Is there a feature in `attrs` that you depend on?

> I presume I cannot use dictionaries for arbitrary data sharing (given the requirement to use dataclasses).

Correct, but within a dataclass you can have untyped dictionaries: https://datafiles.readthedocs.io/en/latest/types/containers/#dictionaries

> Is there anyway I can use datafiles to share a dict objects between processes?

```
from typing import Dict

from datafiles import datafile, field

@datafile("example.yml")
class Container:
    data: Dict = field(default_factory=dict)
```

Then in process one:

```
>>> container = Container({'abc': 123})
```

And process two:

```
>>> container = Container()
>>> print(container.data)
```

**Comment by BrendanSimon** [comment]
Wow.  That's very cool.  I presume only a YAML encoding is possible?

I know other encodings such as CBOR (`cbor2`) or MessagePack perform better than JSON, so I presume they would also perform better than YAML (I should test that assumption).

I've been using `attrs` for a few years now.  It works on Python 2.7 and Python 3.

It's very powerful and `dataclass` is heavily influenced by it, though somewhat stripped.  `attrs` has an `asdict()` and `astuple()`, just like `dataclass`, but not the reverse.

I generally use `cattrs` to do the conversion from class-to-dict and dict-to-class.  It's generic but is `attrs` aware so `attrs` decorated classes are automatically converted without having to register custom hooks.

From that I can then use `json` or `cbor2` to dump the dicts to python neutral format.  I guess YAML could be an option too.

**Comment by BrendanSimon** [comment]
I see JSON and TOML are also supported.

https://datafiles.readthedocs.io/en/latest/formats/

The documentation gives a very brief description of how to create a custom format, but it's not quite enough for me to work out exactly what to do (e.g. if I wanted to add a CBOR format).

Is it possible to give a bit more of skeleton or more snippets of what is required.  e.g. How to extend the `Formatter` class and what to do with it.

**Comment by jacebrowning** [comment]
I've updated the documentation to clarify how to extend the base `Format` class: https://datafiles.readthedocs.io/en/latest/formats/#custom

I'd also recommend checking out the other formatters as examples: https://github.com/jacebrowning/datafiles/blob/main/datafiles/formats.py

**Comment by BrendanSimon** [comment]
Thanks.  I'll take a look.  I did notice a typo in the heading "Map Exiting" instead of "Map Existing" :)

**Comment by BrendanSimon** [comment]
I tried your untyped dictionaries suggestion, but I'm getting the error 

```
TypeError: Annotation is not a type: ~KT
```

I'm using Python 3.7.8 (32-bit on Windows)

Here is the code:

```python
from typing import Dict
from datafiles import datafile, field

@datafile( "datafiles_example.yml" )
class Container :
    data : Dict = field( default_factory=dict )

#! set container object (empty dict) - updates file
container_1 = Container( { 'abc' : 123 } )
print( f"container_1 = {container_1!r}" )

#! read container object from file (no constructor args)
container_2 = Container()
print( f"container_2 = {container_2!r}" )
```

**Comment by BrendanSimon** [comment]
Also noticed `master` branch is at `v0.10` tag.  Should it be at `v0.11`?

**Comment by jacebrowning** [comment]
Sorry, the `Dict` annotation _does_ require types, so `Dict[str, int]` in your example.

The `v0.11` tag is on the `main` branch.

**Comment by jacebrowning** [comment]
@BrendanSimon anything else I can help out with in setting up a custom formatter? If not, I'll mark this closed.

**Comment by BrendanSimon** [comment]
I don't believe so.  I'm happy for you to close the issue.
