### ISSUE TITLE
Modification of nested mutable structures

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#204]
Consider the following YAML file:

```
$ cat config.yml
name: Test
roles:
  category1:
    - value1
    - value2
  category2:
    - something
    - else
```

If I load this datafile using `auto()`, the nested structures under `roles` key are correctly recognized, however, modifications of mutable objects are not projected into the datafile. The following does _not_ alter the content of the `config.yml` file:

```python
>>> from datafiles import auto
>>> config = auto("config.yml")
>>> config.roles['category1']
['value1', 'value2']
>>> config.roles['category1'].append('new_value')
>>> 
```

As a workaround, doing the following works:
```python
>>> from datafiles import auto
>>> config = auto("config.yml")
>>> roles = config.roles
>>> roles['category1'].append('new_value')
>>> config.roles = roles
```

**Comment by tbabej** [comment]
Another option is to explicitly call `save()` on the underlying datafile:

```python
>>> config.datafile.save()
```

**Comment by jacebrowning** [comment]
Thanks for the clear bug report!

I think https://github.com/jacebrowning/datafiles/pull/205 should fix this, which is published here: https://pypi.org/project/datafiles/0.13b4/

**Comment by tbabej** [comment]
I can confirm the `0.13b4` release fixes the issue for me. Thanks for the quick fix!
