### ISSUE TITLE
Handling of default values is not consistent in get_or_create

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#206]
I'm trying to utilize a dataclass to handle a configuration file with a certain mandatory sections. In general, there are two situations that can come up:
1. The config file does not exist yet (running the program first time)
2. The config file exists and is loaded

Interestingly enough, the handling of default values is different in these two cases. Consider the following `datafile` instance:
```python
@datafile("config.yml")
class Config:
    name: str = None
    channels: Dict[str, str] = None
    roles: Dict[str, List[str]] = None
```

Using `get_or_create` with the `config.yml` file missing produces an instance of the datafile where the values of the attributes are `None`.

```python
>>> Config.objects.get_or_create()
Config(name=None, channels=None, roles=None)
```

However, if the file exists (even if empty), the default values of the attributes will correspond to their types (empty string for str, empty dicts for Dict):

```python
>>> Config.objects.get_or_create()
Config(name='', channels={}, roles={})
```

**Comment by tbabej** [comment]
A workaround involves making sure the file exists prior to calling `get_or_create`, that is either:
* calling `get_or_create` twice:
  ```python
   Config.objects.get_or_create()
   return Config.objects.get_or_create()
  ```

* or touching the file prior to calling the `get_or_create`:
  ```python
  import pathlib
  pathlib.Path("config.yml").touch()
  return Config.objects.get_or_create()
  ```

**Comment by jacebrowning** [comment]
Which behavior would you expect?

FWIW, the `Config` class you defined will be rejected by `mypy` as it expects each of your attributes to be `Optional` since you're using `None` as the default.

**Comment by tbabej** [comment]
True, I am indeed skirting beyond the line of correct (typed) Python here. Both of the following alternatives work as expected:

1) This produces `Config(name=None, channels=None, roles=None)` in first and subsequent runs:
```python
@datafile("config.yml")
class Config:
    name: Optional[str] = None
    channels: Optional[dict[str, str]] = None
    roles: Optional[dict[str, list[str]]] = None

print(Config.objects.get_or_create())
```

2) This produces `Config(name='', channels={}, roles={})` in first and subsequent runs:
```python
@datafile("config.yml")
class Config:
    name: str = field(default_factory=str)
    channels: dict[str, str] = field(default_factory=dict)
    roles: dict[str, list[str]] = field(default_factory=dict)
```

**Comment by jacebrowning** [comment]
Thanks for testing that!

Assuming datafiles accepts `value: str = None`, what should be the initial and subsequent value, `None` or `""`?

**Comment by tbabej** [comment]
I would also lean towards coercing values into appropriate types, i.e. `""` being the default.

**Comment by jacebrowning** [comment]
I think https://github.com/jacebrowning/datafiles/pull/207 should take care of this, which is published here: https://pypi.org/project/datafiles/0.13b5/
