### ISSUE TITLE
Datafiles with parametrized paths create empty files with manual=True

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#216]
If `manual=True` or `auto_save=False` is set, the datafiles with parametrized paths do not save the data on the disk:

```python
from datafiles import datafile

@datafile("data/{self.key}.yml", manual=True)
class TestParametrized:
    key: str

@datafile("data/normal.yml", manual=True)
class TestNormal:
    key: str

b = TestNormal("hello")
print(b.datafile._get_data())  # works as expected
b.datafile.save()

a = TestParametrized("hello")
print(a.datafile._get_data())   # prints empty dict
a.datafile.save()
```

**Comment by jacebrowning** [comment]
Let me know if I'm misunderstanding, but this is the intended behavior:

> Attributes included in the filename pattern are automatically excluded from the file contents.

https://datafiles.readthedocs.io/en/latest/api/model/

---

The reason for this is that the value of `model.key` is defined by the path of the file. If `key` was also included in the marshaled data then there could be ambiguous situations if a file is both renamed and modified.

Do you have a specific use case in mind where you need the "primary keys" to show up in files?

**Comment by tbabej** [comment]
No, this makes perfect sense. I missed that particular line in the docs (as parametrized keys are demoed earlier). I was digging further, thinking this was a bug, but this was indeed looking too deliberate:

https://github.com/jacebrowning/datafiles/blob/306c908c0bcf1c7b1f28603956ee725a41d5f6bd/datafiles/mapper.py#L292-L293

Also, it seems I have gotten myself confused when reporting this - the behaviour is consistent in both `manual=True` or `manual=False` case, both behave as you describe.

Closing as invalid.
