### ISSUE TITLE
Can datafiles be used with the backported dataclasses for python 3.6

### ISSUE THREAD

**Issue by andrewv99** [jacebrowning/datafiles#217]
Hi,

I am currently constrained to python 3.6, and already use the backport of dataclasses here:
https://pypi.org/project/dataclasses/

Is it possible to relax the python version constraint for datafiles and add 3.6 - and in that case, have a dependency on the above-mentioned dataclasses package ?

Thanks

**Comment by jacebrowning** [comment]
Thanks for the tip about the `dataclassses` backport!

I gave it a try in https://github.com/jacebrowning/datafiles/pull/218, but it looks like recent releases of IPython/Jupyter have stopped supporting Python 3.6. If you're able to create a similar PR that passes CI, I'd be happy to merge it, but it looks more involved then simply adding `dataclasses` as a dependency.

**Comment by jacebrowning** [comment]
I don't think I'm going to pursue this.
