### ISSUE TITLE
What is the use case for auto_load and auto_save having mismatched values?

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#223]
Related to #222, I was possibly, perhaps mistakenly, using `auto_save=False` when a more proper flag would have been `manual=True`. As a result, I'm wondering if there is a valid use case where these flags are mismatched?

In what situation would user want to use:
* `auto_save=True`, but `auto_load=False`?
* `auto_load=True`, but `auto_save=False`?

**Comment by jacebrowning** [comment]
`auto_load`/`auto_save` have been removed from the documentation and will be dropped in a future version.
