### ISSUE TITLE
No extension is not currently mapped to YAML

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#229]
The documentation states that "no extension" will be mapped to YAML:

https://github.com/jacebrowning/datafiles/blob/main/docs/formats.md#yaml

However, this seems to be in conflict [with the current implementation](https://github.com/jacebrowning/datafiles/blob/64acda4498cfe002b847f0e5199009a93916ce8f/datafiles/formats.py#L78):
```python
class YAML(Formatter):
    """Formatter for (round-trip) YAML Ain't Markup Language."""

    @classmethod
    def extensions(cls):
        return {'.yml', '.yaml'}
```

I suppose two should be reconciled, but what is the source of the ground truth here? Docs or the implementation?

**Comment by jacebrowning** [comment]
Thanks for the report! The docs were always the intended behavior, but I guess it was never tested.
