### ISSUE TITLE
Nested dataclass fails to save when using default arguments

### ISSUE THREAD

**Issue by Seanny123** [jacebrowning/datafiles#231]
I get an unexpected result when running the following code:
```python
from dataclasses import dataclass
from typing import Optional

from datafiles import datafile


@dataclass
class Nested:
    alpha: str = "a"
    beta: str = "b"


@datafile('files/nested_dataclass.yml')
class Sample:
    foo: int = 2
    bar: Optional[Nested] = None


#sample = Sample.objects.get_or_create()
sample = Sample(foo=2, bar=Nested("a", "b"))
print(sample)
sample.datafile.save()
```

Given the contents confirmed by the `print` statement, I expect the dataclass to be represented as:
```
bar:
  alpha: a
  beta: b
foo: 2
```

However, the result instead is missing the attribute `foo: 2`:
```
bar:
  alpha: a
  beta: b
```

If I changed the `Sample` class to not use default arguments:
```python
@datafile('files/nested_dataclass.yml')
class Sample:
    foo: int
    bar: Optional[Nested]
```

I get the expected result.

This is a reduced test case of a more confusing problem I'm having with similar code:
```python
import dataclasses
import typing

import datafiles


@dataclasses.dataclass
class BackendSpec:
    type: str = 'local'
    url: str = ''


@datafiles.datafile('files/hard_fail.yml', manual=True)
class Config:
    backend: BackendSpec = dataclasses.field(default_factory=BackendSpec)
    modules: typing.Optional[list[str]] = None


config = Config.objects.get_or_create()


config.modules = ["okay"]
print(config)
config.datafile.save()
```

Where the saved result is:
```
backend: {}
modules:
  - okay
```

I'm using datafiles 0.15.1. I think these two unexpected results are related, but I'm not sure how.

**Comment by jacebrowning** [comment]
Unless I'm misunderstanding, what you're describing is actually the expected behavior, mentioned [here](https://datafiles.readthedocs.io/en/v0.15.1/):

> Object changes are automatically saved to disk and only include the minimum data needed to restore each object.

Since the default value for `Sample.foo` is `2`, that attribute does not need to be persisted on disk:


```
...

from datafiles import Missing

sample = Sample(foo=2, bar=Nested("a", "b"))

assert sample2.foo == 2
assert sample2.bar.alpha == "a"
assert sample2.bar.beta == "b"

sample2 = Sample()

assert sample2.foo == 2
assert sample2.bar.alpha == "a"
assert sample2.bar.beta == "b"
```

If you want to serialize attribute values that are technically redundant, that can be enabled with the `defaults=True` [option](https://datafiles.readthedocs.io/en/v0.15.1/api/model/):

```
@datafile("files/nested_dataclass.yml", defaults=True)
class Sample:
    foo: int = 2
    bar: Optional[Nested] = None
```
 
Does that make sense? Could I do more to explain the default behavior in the documentation?

**Comment by Seanny123** [comment]
That makes complete sense. I don't know how you could have made it clearer.
