### ISSUE TITLE
YAML: List of dictionaries is serialized with excessive indentation

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#250]
Serializing a Python dictionary works fine using the YAML serialize method:

```python
>>> import datafiles
>>> print(datafiles.formats.YAML.serialize({"one": 1, "two": 2}))
one: 1
two: 2
```

However, if the dictionary is encapsulated in a list, an extra layer indentation is added after the first key-value pair:
```python
>>> print(datafiles.formats.YAML.serialize([{"one": 1, "two": 2}]))
- one: 1
    two: 2
```

where in this case a valid YAML output would be
```yaml
- one: 1
  two: 2
```

**Comment by jacebrowning** [comment]
The fix for this should be available here: https://pypi.org/project/datafiles/1.1b3/

**Comment by tbabej** [comment]
I can confirm this release fixes the issue.
